### PR TITLE
Highly Optimize Tick Loop

### PR DESCRIPTION
**Pull request by pisaiah**
I'll save you the time to port the optimized tick loop.
This adds Spigot's highly optimized tick loop.

Ports commit: https://github.com/fungus-soft/bukkit4fabric/commit/4e0fd6bf2ba9ee6742d1792df19ba2ce2b95d51a

### CODE REVIEW

**Review by hYdos — APPROVED** [review]
the overwrite maybe isnt the best idea (carpet mod has a way to do it without overwriting) but it's fine for now. Thanks

**Review by CoolMineman — COMMENTED** [review]
illegal don't use spigot code

**Comment by hYdos** [comment]
already changed the whole method :tiny_potato:

**Review by CoolMineman — COMMENTED** [review]
Actually fukkit is illegal already, so fukkit.

**Pull request merged**
